<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pricing extends Model
{
    use HasFactory;
    protected $table = "pricings";
    const MUST_AMOUNT_DEFAULT_VALUE = 0;

    const CONTENT_DETAIL_TYPE_TITLE = 1;
    const CONTENT_DETAIL_TYPE_TEXT = 2;
    const CONTENT_DETAIL_TYPE_IMAGE = 3;
    const CONTENT_DETAIL_TYPE_QUOTE = 4;
    const CONTENT_DETAIL_TYPE_KURASHIRU_1 = 5;
    const CONTENT_DETAIL_TYPE_KURASHIRU_3_VERTICAL = 6;
    const CONTENT_DETAIL_TYPE_KURASHIRU_3_HORIZONTAL = 7;
    const CONTENT_DETAIL_TYPE_CAPTION = 8;
    const CONTENT_DETAIL_TYPE_EMBEDDED = 9;
    const CONTENT_DETAIL_TYPE_KURASHIRU_1_SQUARE = 10;

    const DISTRIBUTION_TARGET_TYPE_ALL = 0;
    const DISTRIBUTION_TARGET_TYPE_MEMBERSHIP_CARD_CSV = 1;
    const DISTRIBUTION_TARGET_TYPE_DELIVERY = 2;
    const DISTRIBUTION_TARGET_TYPE_MEMBERSHIP_CARD = 3;
    const DISTRIBUTION_TARGET_TYPE_SHOP = 4;
    const DISTRIBUTION_TARGET_TYPE_CLUSTER_SPECIFICATION = 5;

    const DISTRIBUTION_STATUS_UNDELIVERED = 0;
    const DISTRIBUTION_STATUS_DELIVERED = 1;
    const DISTRIBUTION_STATUS_UNSUBSCRIBE = 2;

    const DISTRIBUTION_STATUS_DISPLAY_DRAFT = 1;
    const DISTRIBUTION_STATUS_DISPLAY_RELEASED = 2;
    const DISTRIBUTION_STATUS_DISPLAY_OPEN = 3;
    const DISTRIBUTION_STATUS_DISPLAY_END = 4;
    const DISTRIBUTION_STATUS_DISPLAY_STOP = 5;

    const MY_PROFIT_GRANT_PRODUCT_YES = 1;
    const MY_PROFIT_GRANT_PRODUCT_NONE = 2;

    const BLOCK_IMAGE_LIMIT = 10;

    const UPLOAD_DIR = 'assets/pricings/';
    const MEMBER_CARD_ERROR_DIR = 'member-card-error/pricings/';

    const MY_PROFIT_GRANT_KEY_ROUTE = "my-profit-grant";
    const MY_PROFIT_DELIVERY_KEY_ROUTE = "my-profit-delivery";
    const PRICING_DELIVERY_JAN_TYPE_PRODUCT = 1;
    const PRICING_DELIVERY_JAN_TYPE_CATEGORY = 2;
    const PRICING_DELIVERY_JAN_TYPE_PRODUCT_CSV = 3;
    const PRICING_DELIVERY_PRODUCT_TYPE_QUANTITY = 1;
    const PRICING_DELIVERY_PRODUCT_TYPE_AMOUNT = 2;

    const JAN_TYPE_NONE = 0;
    const JAN_TYPE_PRODUCT = 1;
    const JAN_TYPE_CATEGORY = 2;
    const JAN_TYPE_PRODUCT_CSV = 3;
    const PRODUCT_TYPE_QUANTITY = 1;
    const PRODUCT_TYPE_AMOUNT = 2;

    const PROJECT_NUMBER_PRICE = 1;

    const AND_TYPE_LOGIC = 2;
    const OR_TYPE_LOGIC = 1;
    const NASI_TYPE_LOGIC = 0;

    const PURCHASE_TARGET_EVERYONE = 0;
    const PURCHASE_TARGET_STORE = 1;
    const JAN_BOX_MAX = 2;

    const TIME_BONUS_SELECTED = 1;
    const TIME_BONUS_NOT_SELECTED = 0;

    const AGGREGATION_METHOD_ABOVE = 1;
    const AGGREGATION_METHOD_BELOW = 2;

    const CAUTION_MAX_LENGTH = 500;

    const TARGET_ALL = 0;
    const TARGET_APP_MEMBER = 1;
    const TARGET_COLLABORATION_MEMBER = 2;
    const TARGET_DISTRIBUTION = 3;
    const TARGET_COLLABORATION_DISTRIBUTION_MEMBER_ = 5;
    const TARGET_APP_MEMBER_DISTRIBUTION_MEMBER_ = 6;

}
